### ISSUE TITLE
Dictionary changed size during iteration

### ISSUE THREAD

**Issue by bsquizz** [RedHatInsights/bonfire#232]
Ran into this while working locally:

```
  File "/home/bsquizza/repos/bonfire/bonfire/openshift.py", line 110, in _all_resources_ready
    for k, r in watcher.resources.items():
RuntimeError: dictionary changed size during iteration
ERROR: deploy failed: dictionary changed size during iteration
```

Need to copy the dict while iterating over it.

**Comment by Victoremepunto** [comment]
Hey ! we hit this one !

in case it helps:

```
bonfire deploy compliance --no-remove-resources compliance --no-remove-resources rbac 
2022-07-22 10:47:10 [    INFO] [          MainThread] Checking for existing reservations for 'Victoremepunto'
2022-07-22 10:47:11 [    INFO] [          MainThread] processing namespace reservation
2022-07-22 10:47:11 [    INFO] [          MainThread] running (pid 1461382): oc apply -f - 
2022-07-22 10:47:14 [    INFO] [         pid-1461382]  |stdout| ##REDACTED##
2022-07-22 10:47:14 [    INFO] [          MainThread] waiting for reservation 'bonfire-reservation-55cd27fa' to get picked up by operator
2022-07-22 10:47:15 [    INFO] [          MainThread] namespace 'ephemeral-auqhne' is reserved by 'Victoremepunto' for '1h' from the default pool
2022-07-22 10:47:16 [    INFO] [          MainThread] namespace console url: ##REDACTED##
2022-07-22 10:47:19 [    INFO] [          MainThread] processing app templates...
2022-07-22 10:47:19 [    INFO] [          MainThread] reading config from: /home/vmugicag/.config/bonfire/config.yaml
2022-07-22 10:47:19 [    INFO] [          MainThread] fetching apps config using source: appsre, target env: insights-ephemeral
2022-07-22 10:47:22 [    INFO] [          MainThread] target env is 'ephemeral' with no ref env given, using 'master' for all apps
2022-07-22 10:47:22 [    INFO] [          MainThread] local app configuration overrides found for: ['compliance_custom', 'app1', 'floorist_custom', 'foobar_app', 'custom-content-sources-backend']
2022-07-22 10:47:22 [    INFO] [          MainThread] processing app 'compliance'
2022-07-22 10:47:22 [    INFO] [          MainThread] processing component compliance-ssg
2022-07-22 10:47:24 [    INFO] [          MainThread] failed to fetch git ref 'master' (http code: 404, response txt: {"message":"404 Branch Not Found"})
2022-07-22 10:47:24 [    INFO] [          MainThread] trying alternate: main
2022-07-22 10:47:24 [    INFO] [          MainThread] fetch succeeded for ref 'main'
2022-07-22 10:47:24 [    INFO] [          MainThread] processing component compliance
2022-07-22 10:47:25 [    INFO] [          MainThread] fetch succeeded for ref 'master'
2022-07-22 10:47:26 [    INFO] [          MainThread] processing component ingress
2022-07-22 10:47:26 [    INFO] [          MainThread] fetch succeeded for ref 'master'
2022-07-22 10:47:26 [    INFO] [          MainThread] processing component puptoo
2022-07-22 10:47:27 [    INFO] [          MainThread] fetch succeeded for ref 'master'
2022-07-22 10:47:27 [    INFO] [          MainThread] processing component storage-broker
2022-07-22 10:47:28 [    INFO] [          MainThread] fetch succeeded for ref 'master'
2022-07-22 10:47:28 [    INFO] [          MainThread] processing component host-inventory
2022-07-22 10:47:29 [    INFO] [          MainThread] fetch succeeded for ref 'master'
2022-07-22 10:47:29 [    INFO] [          MainThread] processing component xjoin-search
2022-07-22 10:47:30 [    INFO] [          MainThread] fetch succeeded for ref 'master'
2022-07-22 10:47:30 [    INFO] [          MainThread] processing component rbac
2022-07-22 10:47:31 [    INFO] [          MainThread] fetch succeeded for ref 'master'
2022-07-22 10:47:31 [    INFO] [          MainThread] processing component compliance-frontend
2022-07-22 10:47:32 [    INFO] [          MainThread] fetch succeeded for ref 'master'
2022-07-22 10:47:32 [    INFO] [          MainThread] ignoring component compliance-frontend, user opted to disable frontend deployments
2022-07-22 10:47:32 [    INFO] [          MainThread] applying app configs...
2022-07-22 10:47:32 [    INFO] [          MainThread] running (pid 1461637): oc apply -f - -n ephemeral-auqhne 
2022-07-22 10:47:34 [    INFO] [         pid-1461637]  |stdout| clowdapp.cloud.redhat.com/compliance-ssg created
2022-07-22 10:47:35 [    INFO] [         pid-1461637]  |stdout| clowdapp.cloud.redhat.com/compliance created
2022-07-22 10:47:35 [    INFO] [         pid-1461637]  |stdout| floorplan.metrics.console.redhat.com/compliance created
2022-07-22 10:47:36 [    INFO] [         pid-1461637]  |stdout| clowdapp.cloud.redhat.com/ingress created
2022-07-22 10:47:36 [    INFO] [         pid-1461637]  |stdout| clowdapp.cloud.redhat.com/puptoo created
2022-07-22 10:47:36 [    INFO] [         pid-1461637]  |stdout| clowdapp.cloud.redhat.com/storage-broker created
2022-07-22 10:47:37 [    INFO] [         pid-1461637]  |stdout| configmap/storage-broker-map created
2022-07-22 10:47:37 [    INFO] [         pid-1461637]  |stdout| clowdapp.cloud.redhat.com/host-inventory created
2022-07-22 10:47:37 [    INFO] [         pid-1461637]  |stdout| clowdjobinvocation.cloud.redhat.com/host-synchronizer-1 created
2022-07-22 10:47:38 [    INFO] [         pid-1461637]  |stdout| clowdjobinvocation.cloud.redhat.com/populate-org-id-column-1 created
2022-07-22 10:47:38 [    INFO] [         pid-1461637]  |stdout| service/insights-inventory created
2022-07-22 10:47:38 [    INFO] [         pid-1461637]  |stdout| configmap/floorplan created
2022-07-22 10:47:39 [    INFO] [         pid-1461637]  |stdout| clowdapp.cloud.redhat.com/xjoin-search created
2022-07-22 10:47:39 [    INFO] [         pid-1461637]  |stdout| service/xjoin-search created
2022-07-22 10:47:49 [    INFO] [         pid-1461637]  |stdout| elasticsearch.elasticsearch.k8s.elastic.co/xjoin-elasticsearch created
2022-07-22 10:47:50 [    INFO] [         pid-1461637]  |stdout| xjoinpipeline.xjoin.cloud.redhat.com/xjoinpipeline created
2022-07-22 10:47:50 [    INFO] [         pid-1461637]  |stderr| Warning: resource networkpolicies/allow-from-xjoin-operator-namespace is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by oc apply. oc apply should only be used on resources created declaratively by either oc create --save-config or oc apply. The missing annotation will be patched automatically.
2022-07-22 10:47:50 [    INFO] [         pid-1461637]  |stdout| networkpolicy.networking.k8s.io/allow-from-xjoin-operator-namespace configured
2022-07-22 10:47:50 [    INFO] [         pid-1461637]  |stdout| configmap/xjoin created
2022-07-22 10:47:51 [    INFO] [         pid-1461637]  |stdout| clowdapp.cloud.redhat.com/rbac created
2022-07-22 10:47:51 [    INFO] [         pid-1461637]  |stdout| configmap/rbac-env created
2022-07-22 10:47:52 [    INFO] [         pid-1461637]  |stdout| configmap/rbac-config created
2022-07-22 10:47:52 [    INFO] [         pid-1461637]  |stdout| configmap/model-access-permissions created
2022-07-22 10:47:52 [    INFO] [         pid-1461637]  |stdout| secret/rbac-psks created
2022-07-22 10:47:52 [    INFO] [         pid-1461637]  |stderr| Warning: resource secrets/insights-rbac is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by oc apply. oc apply should only be used on resources created declaratively by either oc create --save-config or oc apply. The missing annotation will be patched automatically.
2022-07-22 10:47:53 [    INFO] [         pid-1461637]  |stdout| secret/insights-rbac configured
2022-07-22 10:47:53 [    INFO] [         pid-1461637]  |stdout| secret/rbac-secret created
2022-07-22 10:47:53 [    INFO] [         pid-1461637]  |stdout| service/rbac created
2022-07-22 10:47:53 [    INFO] [          MainThread] waiting on resources for max of 600sec...
2022-07-22 10:47:55 [    INFO] [          MainThread] [clowdenvironment/env-ephemeral-auqhne] waiting up to 600sec for resource to be 'ready'
2022-07-22 10:48:01 [    INFO] [          MainThread] [clowdenvironment/env-ephemeral-auqhne] owned resource deployment/env-ephemeral-auqhne-featureflags is ready!
2022-07-22 10:48:01 [   ERROR] [          MainThread] hit unexpected error!
Traceback (most recent call last):
  File "/home/vmugicag/.local/lib/python3.10/site-packages/bonfire/bonfire.py", line 1058, in _cmd_config_deploy
    _wait_on_namespace_resources(ns, timeout)
  File "/home/vmugicag/.local/lib/python3.10/site-packages/bonfire/bonfire.py", line 181, in _wait_on_namespace_resources
    wait_for_all_resources(namespace, timeout)
  File "/home/vmugicag/.local/lib/python3.10/site-packages/bonfire/openshift.py", line 146, in wait_for_all_resources
    wait_for(
  File "/home/vmugicag/.local/lib/python3.10/site-packages/wait_for/__init__.py", line 176, in wait_for
    out = func(*func_args, **func_kwargs)
  File "/home/vmugicag/.local/lib/python3.10/site-packages/bonfire/openshift.py", line 92, in _all_resources_ready
    if not waiter.wait_for_ready(timeout):
  File "/home/vmugicag/.local/lib/python3.10/site-packages/ocviapy/__init__.py", line 673, in wait_for_ready
    wait_for(
  File "/home/vmugicag/.local/lib/python3.10/site-packages/wait_for/__init__.py", line 176, in wait_for
    out = func(*func_args, **func_kwargs)
  File "/home/vmugicag/.local/lib/python3.10/site-packages/ocviapy/__init__.py", line 650, in _check_with_periodic_log
    if self.check_ready():
  File "/home/vmugicag/.local/lib/python3.10/site-packages/ocviapy/__init__.py", line 645, in check_ready
    self._observe(self.resource)
  File "/home/vmugicag/.local/lib/python3.10/site-packages/ocviapy/__init__.py", line 621, in _observe
    for _, r in self.watcher.resources.items():
RuntimeError: dictionary changed size during iteration
2022-07-22 10:48:01 [    INFO] [          MainThread] releasing namespace 'ephemeral-auqhne'
2022-07-22 10:48:02 [    INFO] [          MainThread] processing namespace reservation
2022-07-22 10:48:02 [    INFO] [          MainThread] running (pid 1461892): oc apply -f - 
2022-07-22 10:48:08 [    INFO] [         pid-1461892]  |stdout| ##REDACTED##
2022-07-22 10:48:08 [    INFO] [          MainThread] releasing reservation 'bonfire-reservation-55cd27fa' namespace 'ephemeral-auqhne'
ERROR: deploy failed: dictionary changed size during iteration
```
