### ISSUE TITLE
Traceback on first invocation after install

### ISSUE THREAD

**Issue by catastrophe-brandon** [RedHatInsights/bonfire#27]
After installing bonfire as described in the readme, I tried to invoke the command and got a traceback.

```During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/reavis/.local/bin/bonfire", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 39.2.0 (/usr/lib/python3.6/site-packages), Requirement.parse('setuptools>=40.3.0'), {'google-auth'})```

I'm guessing the version conflict has something to do with the version of python or setuptools that I have installed. I'll try with a more recent version of Python to see if the problem persists. If a newer version makes this issue go away, then it might be worth mentioning the version requirement in the readme.

**Comment by catastrophe-brandon** [comment]
`pip install --upgrade setuptools` did the trick.
