### ISSUE TITLE
Error message for a failed git fetch should give the name of the repository

### ISSUE THREAD

**Issue by catastrophe-brandon** [RedHatInsights/bonfire#282]
When I tried to use bonfire to deploy an application I received errors like the following:

```
2023-01-17 15:44:15 [    INFO] [          MainThread] fetching apps config using source: appsre, target env: insights-ephemeral
2023-01-17 15:44:17 [    INFO] [          MainThread] target env is 'ephemeral' with no ref env given, using 'master' for all apps
2023-01-17 15:44:17 [    INFO] [          MainThread] local app configuration overrides found for: ['my_custom_app']
2023-01-17 15:44:17 [    INFO] [          MainThread] processing app 'advisor'
2023-01-17 15:44:17 [    INFO] [          MainThread] processing component tasks-frontend
2023-01-17 15:44:17 [    INFO] [          MainThread] failed to fetch git ref 'master' (http code: 401, response txt: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"})
2023-01-17 15:44:17 [    INFO] [          MainThread] trying alternate: main
2023-01-17 15:44:18 [    INFO] [          MainThread] failed to fetch git ref 'main' (http code: 401, response txt: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"})
2023-01-17 15:44:18 [    INFO] [          MainThread] trying alternate: stable
2023-01-17 15:44:18 [    INFO] [          MainThread] failed to fetch git ref 'stable' (http code: 401, response txt: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"})
2023-01-17 15:44:18 [   ERROR] [          MainThread] failed to fetch template file for tasks-frontend
2023-01-17 15:44:18 [   ERROR] [          MainThread] hit fatal error: git ref fetch failed for 'master' and its alternates: main, stable, see logs for details
```

It would be a useful enhancement to add the name of the repository when a git fetch fails. The problem in this case is clearly related to my credentials, but it would be insightful to know which content is being pulled down for the sake of troubleshooting.

**Comment by bsquizz** [comment]
Question -- if you run `bonfire --debug <args>` does that give you the info you need? We might just need to switch a 'log.debug' that is printing the URL to a 'log.info' or 'log.error'

**Comment by catastrophe-brandon** [comment]
It looks like I do get more information. Here's example output:

```
2023-01-17 15:56:20 [   DEBUG] [          MainThread] Starting new HTTPS connection (1): api.github.com:443
2023-01-17 15:56:20 [   DEBUG] [          MainThread] https://api.github.com:443 "GET /repos/RedHatInsights/tasks-frontend/git/refs/heads/master HTTP/1.1" 401 80
2023-01-17 15:56:20 [    INFO] [          MainThread] failed to fetch git ref 'master' (http code: 401, response txt: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"})
2023-01-17 15:56:20 [    INFO] [          MainThread] trying alternate: main
2023-01-17 15:56:20 [   DEBUG] [          MainThread] attempting ref 'main'
2023-01-17 15:56:20 [   DEBUG] [          MainThread] https://api.github.com:443 "GET /repos/RedHatInsights/tasks-frontend/git/refs/heads/main HTTP/1.1" 401 80
2023-01-17 15:56:20 [    INFO] [          MainThread] failed to fetch git ref 'main' (http code: 401, response txt: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"})
2023-01-17 15:56:20 [    INFO] [          MainThread] trying alternate: stable
2023-01-17 15:56:20 [   DEBUG] [          MainThread] attempting ref 'stable'
2023-01-17 15:56:20 [   DEBUG] [          MainThread] https://api.github.com:443 "GET /repos/RedHatInsights/tasks-frontend/git/refs/heads/stable HTTP/1.1" 401 80
2023-01-17 15:56:20 [    INFO] [          MainThread] failed to fetch git ref 'stable' (http code: 401, response txt: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"})
2023-01-17 15:56:20 [   ERROR] [          MainThread] failed to fetch template file for tasks-frontend
2023-01-17 15:56:20 [   DEBUG] [          MainThread] Traceback (most recent call last):
  File "/home/btweed/bonfire_venv/lib64/python3.8/site-packages/bonfire/processor.py", line 475, in _get_component_items
    commit, template_content = rf.fetch()
  File "/home/btweed/bonfire_venv/lib64/python3.8/site-packages/bonfire/utils.py", line 199, in fetch
    result = self._fetch_github()
  File "/home/btweed/bonfire_venv/lib64/python3.8/site-packages/bonfire/utils.py", line 340, in _fetch_github
    commit = self._get_gh_commit_hash()
  File "/home/btweed/bonfire_venv/lib64/python3.8/site-packages/bonfire/utils.py", line 333, in _get_gh_commit_hash
    response = self._get_ref(get_ref_func)
  File "/home/btweed/bonfire_venv/lib64/python3.8/site-packages/bonfire/utils.py", line 269, in _get_ref
    raise Exception(
Exception: git ref fetch failed for 'master' and its alternates: main, stable, see logs for details
```

**Comment by catastrophe-brandon** [comment]
The debug flag got me where I needed to go, so I think I'll close this issue. The fix for logging seems like it's probably not worth the effort here, but I could open a different issue for that if needed. Just lmk.
