### ISSUE TITLE
key now found

### ISSUE THREAD

**Issue by dmzoneill** [RedHatInsights/bonfire#59]
I get the below post deployment error from

clowderapp.yaml
https://paste.ubuntu.com/p/dJPtPfN52p/

cloudenv.yaml
https://paste.ubuntu.com/p/x3bcYp4WNF/

bonfire.yaml
https://paste.ubuntu.com/p/jr3rzKTx8r/

    kubectl create namespace demo
    kubectl create namespace rhc
    kubectl apply -f saas-templates/clowdenv.yaml
    bonfire deploy -c bonfire/config.yaml  tower -n demo -e tower

    2021-06-08 16:17:24 [   ERROR] [          MainThread] hit unexpected error!
    Traceback (most recent call last):
    File "/home/ladas1/.local/lib/python3.9/site-packages/bonfire/bonfire.py", line 644, in _cmd_config_deploy
        _wait_on_namespace_resources(ns, timeout)
    File "/home/ladas1/.local/lib/python3.9/site-packages/bonfire/bonfire.py", line 141, in _wait_on_namespace_resources
        wait_for_all_resources(namespace, timeout)
    File "/home/ladas1/.local/lib/python3.9/site-packages/bonfire/openshift.py", line 557, in wait_for_all_resources
        wait_for(
    File "/home/ladas1/.local/lib/python3.9/site-packages/wait_for/__init__.py", line 174, in wait_for
        out = func(*func_args, **func_kwargs)
    File "/home/ladas1/.local/lib/python3.9/site-packages/bonfire/openshift.py", line 510, in _all_resources_ready
        clowd_env_name = find_clowd_env_for_ns(namespace)["metadata"]["name"]
    TypeError: 'NoneType' object is not subscriptable
    ERROR: deploy failed
    make: *** [Makefile.minkube:147: minikube-up] Error 1

id probably upgrade that line to 

    yaml = clowd_env_name = find_clowd_env_for_ns(namespace)
    if 'metadata' in in yaml:
        if 'name' in yaml['metadata']:

**Comment by bsquizz** [comment]
I think the root cause is find_clowd_env_for_ns is returning None and we are not checking for that first before trying to extract the name. Will fix it.

**Comment by bsquizz** [comment]
The cause here is that the `tower` ClowdEnvironment uses `targetNamespace: rhc` while your ClowdApps were deployed to the `demo` namespace. The code was assuming that the `demo` namespace would have a ClowdEnvironment associated with it, which is usually how the ephemeral environments are set up, but technically what you are doing is valid so it was a bad assumption :).

The fix is to check if any ClowdEnvironment has `targetNamespace` set to the namespace you deployed to -- if not we will skip waiting on ClowdEnvironment resources in that namespace.
